load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "SpinLockTest",
    srcs = ["SpinLockTest.cc"],
    deps = [
        "//:core2",
        "@com_google_googletest//:gtest_main",
    ],
)
