load("@rules_cc//cc:defs.bzl", "cc_test")

cc_test(
    name = "VectorTest",
    size = "small",
    srcs = ["VectorTest.cc"],
    deps = [
        "//:core2",
        "@com_google_googletest//:gtest_main",
    ],
)
