load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "corelib",
    hdrs = [
        "ReaderWriterLock.h",
        "All.h",
        "Lib.h",
        "Utility.h",
        "Vector.h",
        "HashMap.h"
    ],
    visibility = ["//bin:__pkg__"],
)
