load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "corelib",
    hdrs = [
        "All.h",
        "Async.h",
        "HashMap.h",
        "Lib.h",
        "ReaderWriterLock.h",
        "String.h",
        "ThreadPool.h",
        "Utility.h",
        "Vector.h",
    ],
    visibility = [
        "//bin:__pkg__",
        "//test:__pkg__",
    ],
)
